### ISSUE TITLE
满文输入似乎难以输入ᡢ

### ISSUE THREAD

**Issue by SyzygyYuan** [shenyileirob/rime_schemata#3]
查遍schema.yaml，未能找到如何输入ᡢ

**Comment by shenyileirob** [comment]
满文 ng 用 U+1829 的「ᠩ」，而锡伯文用 U+1862 的「ᡢ」。你需要的 U+1862 「ᡢ」应该用锡伯文输入法。

**Comment by SyzygyYuan** [comment]
原来如此，应该是「ᠩ」，用;n即可，感谢。
